# 3.5 张量的元素类型

## 3.5.3 管理张量的dtype属性

In [4]:
import torch

In [7]:
# 创建时提供dtype关键字
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
double_points, short_points

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]], dtype=torch.float64),
 tensor([[1, 2],
         [3, 4]], dtype=torch.int16))

In [10]:
short_points.dtype

torch.int16

In [11]:
# 使用相应的类型转换函数
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [13]:
# 使用to方法
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

# 张量的API

### Pytorch官网：https://pytorch.org/docs/stable/index.html?spm=5176.28103460.0.0.297c5d27YPsilD