In [2]:
import imageio
import torch
import os

In [3]:
def Pic2Tensor(pic_dir):
    picture = imageio.imread_v2(pic_dir)
    pic_tensor = torch.from_numpy(picture)
    pic_tensor = pic_tensor.permute(2, 0, 1)
    return pic_tensor

blue = Pic2Tensor("../blue.jpg")
red = Pic2Tensor("../red.png")
green = Pic2Tensor("../green.jpeg")

blue.shape, red.shape, green.shape

(torch.Size([3, 2137, 1180]),
 torch.Size([3, 195, 259]),
 torch.Size([3, 177, 187]))

In [4]:
def Tensor_Mean(tensor):
    tensor = tensor.float()
    print("R pipe = ", torch.mean(tensor[0]).item())
    print(f"G pipe = {torch.mean(tensor[1])}")
    print(f"B pipe = {torch.mean(tensor[2])}")
    print("\n")


Tensor_Mean(blue)
Tensor_Mean(red)
Tensor_Mean(green)

R pipe =  88.17103576660156
G pipe = 203.8483428955078
B pipe = 254.70855712890625


R pipe =  255.0
G pipe = 0.0
B pipe = 0.0


R pipe =  9.0
G pipe = 121.0
B pipe = 49.0




In [43]:
a = torch.arange(1, 13)
a = a.reshape(3, 2, 2).float()
a

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [44]:
weight = torch.tensor([0.2, 0.5, 0.3])
weight

tensor([0.2000, 0.5000, 0.3000])

In [38]:
for i in range(3):
    a[i] = weight[i] * a[i]
a

tensor([[[0.2000, 0.4000],
         [0.6000, 0.8000]],

        [[2.5000, 3.0000],
         [3.5000, 4.0000]],

        [[2.7000, 3.0000],
         [3.3000, 3.6000]]])

In [39]:
a.mean()

tensor(2.3000)

In [45]:
weight_expanded = weight.view(3, 1, 1).expand_as(a)

# 每个元素乘以对应的权重
weighted_a = a * weight_expanded

# 计算所有元素的加权均值
global_weighted_mean = weighted_a.mean().item()

print("Global weighted mean:", global_weighted_mean), weighted_a

Global weighted mean: 2.299999952316284


(None,
 tensor([[[0.2000, 0.4000],
          [0.6000, 0.8000]],
 
         [[2.5000, 3.0000],
          [3.5000, 4.0000]],
 
         [[2.7000, 3.0000],
          [3.3000, 3.6000]]]))